import type { Deck } from '../game/domain/types'

export const decks: Deck[] = [
  { id: 'mocambique', name: 'Moçambique', icon: 'A', wordCount: 80, availableOffline: true, selected: true, words: [
    'Maputo', 'Matapa', 'Chapa', 'Xitique', 'Marrabenta', 'Katembe', 'Ilha de Moçambique', 'Gorongosa', 'Zambeze', 'Capulana', 'Piri-piri', 'Tofo', 'Xima', 'Marracuene', 'Inhambane', 'Niassa', 'Bazaruto', 'Samora Machel', 'Eduardo Mondlane', 'Chimoio',
    'Beira', 'Nampula', 'Pemba', 'Tete', 'Quelimane', 'Xai-Xai', 'Lichinga', 'Vilanculos', 'Ponta do Ouro', 'Limpopo', 'Rovuma', 'Cahora Bassa', 'Chimanimani', 'Gurué', 'Angoche', 'Macuti', 'Mussiro', 'Timbila', 'Tufo', 'Dhow', 'Mercado Central', 'Praça da Independência', 'Costa do Sol', 'Monte Binga', 'Lago Niassa', 'Sena', 'Manica', 'Sofala', 'Gaza', 'Cabo Delgado',
    'Mozal', 'Hidroeléctrica de Cahora Bassa', 'M-Pesa', 'Txopela', 'Machimbombo', 'Mukhero', 'Badjia', 'Chamussa', 'Feijão nhemba', 'Caju', 'Mafurra', 'Mucapata', 'Galinha à zambeziana', 'Camarão', 'Praia do Bilene', 'Reserva do Niassa', 'Parque Nacional do Limpopo', 'Reserva de Maputo', 'Arquipélago das Quirimbas', 'Ponte Maputo-Katembe', 'Fortaleza de Maputo', 'Estação dos CFM', 'Museu de História Natural', 'FEIMA', 'Malangatana', 'José Craveirinha', 'Noémia de Sousa', 'Eusébio', 'Graça Machel', 'Mia Couto',
  ] },
  { id: 'futebol', name: 'Futebol', icon: '◎', wordCount: 80, availableOffline: true, selected: true, words: [
    'Cristiano Ronaldo', 'Lionel Messi', 'Fora de jogo', 'Grande penalidade', 'Liga dos Campeões', 'Moçambola', 'Árbitro', 'Guarda-redes', 'Estádio', 'Benfica', 'Real Madrid', 'Mambas', 'Pontapé de canto', 'Cartão vermelho', 'Hat-trick', 'Médio', 'Capitão', 'Mundial', 'VAR', 'Golo',
    'Premier League', 'La Liga', 'Serie A', 'Bundesliga', 'Liga Europa', 'Taça Africana', 'Livre directo', 'Pontapé de bicicleta', 'Drible', 'Defesa', 'Avançado', 'Adepto', 'Bancada', 'Baliza', 'Apito', 'Relvado', 'Treinador', 'Substituição', 'Prolongamento', 'Desempate por penáltis', 'Troféu', 'Camisola', 'Bola de Ouro', 'Kylian Mbappé', 'Neymar', 'Mohamed Salah', 'Pelé', 'Eusébio', 'José Mourinho', 'Fair play',
    'Manchester United', 'Manchester City', 'Arsenal', 'Liverpool', 'Chelsea', 'Barcelona', 'Juventus', 'AC Milan', 'Bayern Munique', 'Paris Saint-Germain', 'Sporting', 'Porto', 'Costa do Marfim', 'Bafana Bafana', 'Selecção Brasileira', 'Copa do Mundo', 'Taça', 'Rede', 'Luvas', 'Chuteiras', 'Claque', 'Contra-ataque', 'Cabeceamento', 'Túnel', 'Assistência', 'Marcador', 'Lesão', 'Tempo adicional', 'Jogo amigável', 'Mercado de transferências',
  ] },
  { id: 'filmes', name: 'Filmes', icon: '▦', wordCount: 80, availableOffline: true, selected: false, words: [
    'Titanic', 'Pantera Negra', 'O Rei Leão', 'Avatar', 'Vingadores', 'Matrix', 'Frozen', 'Gladiador', 'Jurassic Park', 'Toy Story', 'Homem-Aranha', 'Shrek', 'Rocky', 'Barbie', 'O Padrinho', 'Star Wars', 'Madagáscar', 'Rambo', 'Harry Potter', 'Creed',
    'Interstellar', 'A Origem', 'Forrest Gump', 'Piratas das Caraíbas', 'Missão Impossível', 'Velocidade Furiosa', 'O Senhor dos Anéis', 'Batman', 'Superman', 'Mulher-Maravilha', 'Joker', 'Top Gun', 'Terminator', 'Alien', 'King Kong', 'Godzilla', 'Procurando Nemo', 'Ratatui', 'Up', 'Coco', 'Encanto', 'Moana', 'Aladino', 'Mulan', 'Branca de Neve', 'O Máskara', 'Matrix Reloaded', 'Indiana Jones', 'Karate Kid', 'Duna',
    'E.T.', 'Tubarão', 'Os Caça-Fantasmas', 'Regresso ao Futuro', 'Men in Black', 'Braveheart', 'Náufrago', 'À Procura da Felicidade', 'Slumdog Millionaire', 'Parasitas', 'Tudo em Todo o Lado ao Mesmo Tempo', 'Oppenheimer', 'Bohemian Rhapsody', 'Pantera Cor-de-Rosa', 'Sozinho em Casa', 'As Crónicas de Nárnia', 'A Bela e o Monstro', 'Os Incríveis', 'Monstros e Companhia', 'Vida de Insecto', 'Carros', 'Kung Fu Panda', 'Como Treinares o Teu Dragão', 'Meu Malvado Favorito', 'Divertida-Mente', 'Zootrópolis', 'Os Smurfs', 'Sonic', 'Aquaman', 'Flash',
  ] },
  { id: 'musica', name: 'Música', icon: '♫', wordCount: 80, availableOffline: true, selected: false, words: [
    'Marrabenta', 'Jazz', 'Hip-hop', 'Guitarra', 'Microfone', 'Concerto', 'Bateria', 'Piano', 'Refrão', 'Kizomba', 'Pandza', 'DJ', 'Festival', 'Playlist', 'Dança', 'Banda', 'Rapper', 'Saxofone', 'Melodia', 'Palco',
    'Afrobeat', 'Reggae', 'Rock', 'Pop', 'Ópera', 'Fado', 'Samba', 'Rumba', 'Música clássica', 'Violino', 'Trompete', 'Flauta', 'Baixo', 'Teclado', 'Acordeão', 'Tambor', 'Voz', 'Coro', 'Orquestra', 'Letra', 'Ritmo', 'Harmonia', 'Álbum', 'Single', 'Estúdio', 'Auscultadores', 'Vinil', 'Maestro', 'Karaoke', 'Turné',
    'Marimba', 'Xilofone', 'Ukulele', 'Harpa', 'Violoncelo', 'Clarinete', 'Pandeiro', 'Triângulo', 'Pratos', 'Partitura', 'Nota musical', 'Solo', 'Dueto', 'Remix', 'Videoclipe', 'Rádio', 'Coluna de som', 'Amplificador', 'Festival Azgo', 'Timbila', 'Stewart Sukuma', 'Mingas', 'Neyma', 'Lizha James', 'Wazimbo', 'Burna Boy', 'Beyoncé', 'Michael Jackson', 'Bob Marley', 'Miriam Makeba',
  ] },
  { id: 'africa', name: 'África', icon: '♘', wordCount: 80, availableOffline: true, selected: false, words: [
    'Nelson Mandela', 'Kilimanjaro', 'Saara', 'Nilo', 'União Africana', 'Cairo', 'Lagos', 'Luanda', 'Nairobi', 'Maputo', 'Savanas', 'Baobá', 'Victoria Falls', 'Madagáscar', 'Rift Valley', 'Kalahari', 'Serengeti', 'Timbuktu', 'Casablanca', 'Zanzibar',
    'África do Sul', 'Angola', 'Tanzânia', 'Quénia', 'Nigéria', 'Egipto', 'Etiópia', 'Gana', 'Senegal', 'Marrocos', 'Camarões', 'Ruanda', 'Botsuana', 'Namíbia', 'Zimbabwe', 'Lesoto', 'Eswatini', 'Maurícias', 'Seychelles', 'Cabo Verde', 'Monte Atlas', 'Lago Vitória', 'Rio Congo', 'Delta do Okavango', 'Deserto do Namibe', 'Ilha de Gorée', 'Grande Zimbabwe', 'Monte Quénia', 'Golfo da Guiné', 'Cabo da Boa Esperança',
    'Moçambique', 'Uganda', 'Sudão', 'Sudão do Sul', 'Argélia', 'Tunísia', 'Líbia', 'Mali', 'Guiné-Bissau', 'Guiné Equatorial', 'Gabão', 'Congo', 'República Democrática do Congo', 'Zâmbia', 'Malawi', 'Burkina Faso', 'Costa do Marfim', 'Togo', 'Benim', 'Libéria', 'Serra Leoa', 'Chade', 'Somália', 'Djibuti', 'Eritreia', 'Comores', 'São Tomé e Príncipe', 'Monte Camarões', 'Lago Tanganica', 'Cataratas de Tugela',
  ] },
  { id: 'geral', name: 'Geral', icon: '⊕', wordCount: 80, availableOffline: true, selected: false, words: [
    'WhatsApp', 'Fotossíntese', 'Internet', 'Universidade', 'Satélite', 'Relógio', 'Biblioteca', 'Chocolate', 'Aeroporto', 'Elefante', 'Telefone', 'Hospital', 'Bicicleta', 'Oceano', 'Computador', 'Tempestade', 'Presidente', 'Professor', 'Arco-íris', 'Aniversário',
    'Televisão', 'Geladeira', 'Semáforo', 'Elevador', 'Restaurante', 'Supermercado', 'Farmácia', 'Calendário', 'Espelho', 'Guarda-chuva', 'Mochila', 'Óculos', 'Chave', 'Janela', 'Escada', 'Cozinha', 'Jardim', 'Praia', 'Montanha', 'Deserto', 'Vulcão', 'Planeta', 'Astronauta', 'Dinossauro', 'Borboleta', 'Girafa', 'Golfinho', 'Camaleão', 'Abacaxi', 'Café',
    'Mesa', 'Cadeira', 'Porta', 'Cama', 'Sapato', 'Camisa', 'Chapéu', 'Garrafa', 'Colher', 'Garfo', 'Panela', 'Sabão', 'Toalha', 'Almofada', 'Ventoinha', 'Autocarro', 'Comboio', 'Navio', 'Motocicleta', 'Helicóptero', 'Foguetão', 'Robô', 'Câmara', 'Fotografia', 'Jornal', 'Dicionário', 'Matemática', 'Música', 'Futebol', 'Cinema',
  ] },
]
